package = "my-lua-project"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = "A sample Lux project."
maintainer = "dealenx"
labels = ["learning"]
license = "MIT"

[dependencies]
# Add your dependencies here
# busted = ">=2.0"

[run]
args = ["src/main.lua"]

[build]
type = "builtin"
